const mongoose = require('mongoose');
const Product = require('./models/product');  // Assuming product schema is in 'models/product'

// Connect to MongoDB
mongoose.connect('mongodb://127.0.0.1:27017/mission-05', {
})
  .then(() => {
    console.log("Connected to MongoDB!");

    // Sample products
    const products = [
      {
        title: 'Ergonomic Office Chair',
        description: 'Comfortable ergonomic chair with adjustable armrests and lumbar support. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
        start_price: 120,
        reserve_price: 180,
        buy_now_price: 220,
        current_bid: [140],
        image: 'https://www.smartofficefurniture.co.nz/cdn/shop/files/mondo-brook-mesh-mid-back-chair-smart-office-furniture.webp?v=1733892315&width=533',
        category: 'Furniture',
        subcategory: 'Office Chairs',
        location: 'Auckland, NZ',
        condition: 'New',
        auction_start_date: new Date('2025-04-10T10:00:00'),
        auction_end_date: new Date('2025-04-15T17:00:00'),
        seller_name: 'OfficeMartNZ',
        seller_image: 'https://randomuser.me/api/portraits/men/32.jpg',
        seller_rating: 98,
        seller_location: 'Auckland, NZ',
        seller_member_since: new Date('2021-02-15'),
      },
      {
        title: 'Standing Desk',
        description: 'Adjustable standing desk with electric height adjustment.',
        start_price: 350,
        reserve_price: 500,
        buy_now_price: 620,
        current_bid: [],
        image: 'https://standdesk.nz/wp-content/uploads/2023/07/1500-walnut-black.jpg',
        category: 'Furniture',
        subcategory: 'Desks',
        location: 'Wellington, NZ',
        condition: 'New',
        auction_start_date: new Date('2025-04-12T09:00:00'),
        auction_end_date: new Date('2025-05-20T18:00:00'),
        seller_name: 'WorkSpaceGear',
        seller_image: 'https://randomuser.me/api/portraits/women/45.jpg',
        seller_rating: 95,
        seller_location: 'Wellington, NZ',
        seller_member_since: new Date('2020-08-30'),
      },
      {
        title: 'Gaming Laptop',
        description: 'High-performance laptop with RTX graphics card and 16GB RAM for gaming.',
        start_price: 1500,
        reserve_price: 2000,
        buy_now_price: 2300,
        current_bid: [],
        image: 'https://i.dell.com/is/image/DellContent/content/dam/ss2/product-images/dell-client-products/notebooks/g-series/g16-7630/media-gallery/black/notebook-g16-7630-nt-black-gallery-1.psd?fmt=pjpg&pscan=auto&scl=1&wid=3510&hei=2635&qlt=100,1&resMode=sharp2&size=3510,2635&chrss=full&imwidth=5000',
        category: 'Electronics',
        subcategory: 'Laptops',
        location: 'Auckland, NZ',
        condition: 'Used',
        auction_start_date: new Date('2025-04-10T12:00:00'),
        auction_end_date: new Date('2025-05-14T19:00:00'),
        seller_name: 'NZTechSales',
        seller_image: 'https://randomuser.me/api/portraits/men/29.jpg',
        seller_rating: 91,
        seller_location: 'Auckland, NZ',
        seller_member_since: new Date('2019-05-10'),
      },
      {
        title: 'LED Monitor 24" Full HD',
        description: 'Full HD LED monitor with 144Hz refresh rate, perfect for gaming.',
        start_price: 250,
        reserve_price: 350,
        buy_now_price: 400,
        current_bid: [300, 310],
        image: 'https://i.dell.com/is/image/DellContent//content/dam/images/products/electronics-and-accessories/dell/monitors/s-series/s2421hn/s2421hn-cfp-00025lf095-gy.psd?fmt=pjpg&pscan=auto&scl=1&wid=3488&hei=2974&qlt=100,1&resMode=sharp2&size=3488,2974&chrss=full&imwidth=5000',
        category: 'Electronics',
        subcategory: 'Monitors',
        location: 'Christchurch, NZ',
        condition: 'New',
        auction_start_date: new Date('2025-04-15T14:00:00'),
        auction_end_date: new Date('2025-05-22T16:00:00'),
        seller_name: 'VisualTechNZ',
        seller_image: 'https://randomuser.me/api/portraits/women/12.jpg',
        seller_rating: 97,
        seller_location: 'Christchurch, NZ',
        seller_member_since: new Date('2022-01-01'),
      },
      {
        title: 'Wireless Mouse',
        description: 'Ergonomic wireless mouse with long battery life and fast response.',
        start_price: 30,
        reserve_price: 50,
        buy_now_price: 65,
        current_bid: [38],
        image: 'https://assets.kogan.com/images/mightyape/MPE-30820052/1-2fbbd54b15-218216385.jpeg?auto=webp&bg-color=fff&canvas=1200%2C800&dpr=1&enable=upscale&fit=bounds&height=800&quality=90&width=1200',
        category: 'Accessories',
        subcategory: 'Mice',
        location: 'Hamilton, NZ',
        condition: 'New',
        auction_start_date: new Date('2025-04-18T08:00:00'),
        auction_end_date: new Date('2025-05-25T15:00:00'),
        seller_name: 'ClickZoneNZ',
        seller_image: 'https://randomuser.me/api/portraits/men/57.jpg',
        seller_rating: 92,
        seller_location: 'Hamilton, NZ',
        seller_member_since: new Date('2023-06-25'),
      },
      {
        title: 'Mesh Executive Chair',
        description: 'Breathable mesh executive chair with headrest and adjustable features.',
        start_price: 160,
        reserve_price: 200,
        buy_now_price: 260,
        current_bid: [180, 190, 205],
        image: 'https://assets.kogan.com/images/mightyape/MPE-33543998/1-a3ae920908-233716943.jpeg?auto=webp&bg-color=fff&canvas=1200%2C800&dpr=1&enable=upscale&fit=bounds&height=800&quality=90&width=1200',
        category: 'Furniture',
        subcategory: 'Office Chairs',
        location: 'Auckland, NZ',
        condition: 'New',
        auction_start_date: new Date('2025-04-16T09:00:00'),
        auction_end_date: new Date('2025-05-21T17:00:00'),
        seller_name: 'OfficeMartNZ',
        seller_image: 'https://randomuser.me/api/portraits/men/32.jpg',
        seller_rating: 98,
        seller_location: 'Auckland, NZ',
        seller_member_since: new Date('2021-02-15'),
      },
      {
        title: 'Modern Office Desk',
        description: 'Spacious office desk with drawer units and cable management.',
        start_price: 280,
        reserve_price: 350,
        buy_now_price: 400,
        current_bid: [300, 301],
        image: 'https://assets.kogan.com/images/mightyape/MPE-38394367/1-be4e390082-310948439.jpeg?auto=webp&bg-color=fff&canvas=1200%2C800&dpr=1&enable=upscale&fit=bounds&height=800&quality=90&width=1200',
        category: 'Furniture',
        subcategory: 'Desks',
        location: 'Auckland, NZ',
        condition: 'New',
        auction_start_date: new Date('2025-04-17T10:30:00'),
        auction_end_date: new Date('2025-05-24T18:00:00'),
        seller_name: 'OfficeMartNZ',
        seller_image: 'https://randomuser.me/api/portraits/men/32.jpg',
        seller_rating: 98,
        seller_location: 'Auckland, NZ',
        seller_member_since: new Date('2021-02-15'),
      },
      {
        title: 'Filing Cabinet - 4 Drawer',
        description: 'Durable metal cabinet with lockable drawers for office use.',
        start_price: 100,
        reserve_price: 150,
        buy_now_price: 180,
        current_bid: [120],
        image: 'https://www.warehousestationery.co.nz/dw/image/v2/AAWO_PRD/on/demandware.static/-/Sites-wsl-master-catalog/default/dw3d0efb3c/53/57/W2248746_30.jpg?sw=232&sh=232&sm=fit',
        category: 'Furniture',
        subcategory: 'Storage',
        location: 'Auckland, NZ',
        condition: 'New',
        auction_start_date: new Date('2025-04-14T11:00:00'),
        auction_end_date: new Date('2025-05-21T15:30:00'),
        seller_name: 'OfficeMartNZ',
        seller_image: 'https://randomuser.me/api/portraits/men/32.jpg',
        seller_rating: 98,
        seller_location: 'Auckland, NZ',
        seller_member_since: new Date('2021-02-15'),
      },
      {
        title: 'Ergo Footrest for Desk',
        description: 'Adjustable ergonomic footrest to reduce pressure and improve posture.',
        start_price: 45,
        reserve_price: 60,
        buy_now_price: 75,
        current_bid: [],
        image: 'https://assets.kogan.com/images/mightyape/MPE-37977967/1-a4c662bba9-308156753.jpeg?auto=webp&bg-color=fff&canvas=1200%2C800&dpr=1&enable=upscale&fit=bounds&height=800&quality=90&width=1200',
        category: 'Accessories',
        subcategory: 'Office Accessories',
        location: 'Auckland, NZ',
        condition: 'New',
        auction_start_date: new Date('2025-04-19T13:00:00'),
        auction_end_date: new Date('2025-05-26T17:00:00'),
        seller_name: 'OfficeMartNZ',
        seller_image: 'https://randomuser.me/api/portraits/men/32.jpg',
        seller_rating: 98,
        seller_location: 'Auckland, NZ',
        seller_member_since: new Date('2021-02-15'),
      },
      {
        title: 'Desk Lamp with USB Port',
        description: 'LED desk lamp with adjustable brightness and built-in USB charging port.',
        start_price: 35,
        reserve_price: 50,
        buy_now_price: 65,
        current_bid: [42],
        image: 'https://www.pbtech.co.nz/imgprod/H/O/HOMSPB3309__5.jpg?h=416317244',
        category: 'Accessories',
        subcategory: 'Lighting',
        location: 'Auckland, NZ',
        condition: 'New',
        auction_start_date: new Date('2025-04-20T08:00:00'),
        auction_end_date: new Date('2025-05-27T14:00:00'),
        seller_name: 'OfficeMartNZ',
        seller_image: 'https://randomuser.me/api/portraits/men/32.jpg',
        seller_rating: 98,
        seller_location: 'Auckland, NZ',
        seller_member_since: new Date('2021-02-15'),
      },
      {
        title: 'Bluetooth Speaker',
        description: 'Portable Bluetooth speaker with rich bass and 12-hour battery life.',
        start_price: 20,
        reserve_price: 1,
        buy_now_price: 50,
        current_bid: [],
        category: 'Electronics',
        subcategory: 'Speakers',
        location: 'Wellington, NZ',
        condition: 'New',
        auction_start_date: new Date('2025-04-25T10:00:00'),
        auction_end_date: new Date('2025-05-30T18:00:00'),
        seller_name: 'SoundWaveNZ',
        seller_image: 'https://randomuser.me/api/portraits/women/44.jpg',
        seller_rating: 95,
        seller_location: 'Wellington, NZ',
        seller_member_since: new Date('2022-03-20'),
        image: 'https://www.gadgetsonline.co.nz/cdn/shop/products/jbl-flip-6-portable-ip67-waterproof-bluetooth-speaker-black-657844.jpg?v=1679368012&width=800'
      },
      {
        title: 'Yoga Mat',
        description: 'Eco-friendly yoga mat with non-slip surface.',
        start_price: 15,
        reserve_price: 1,
        buy_now_price: 30,
        current_bid: [18, 22],
        category: 'Fitness',
        subcategory: 'Yoga Equipment',
        location: 'Christchurch, NZ',
        condition: 'New',
        auction_start_date: new Date('2025-04-26T11:00:00'),
        auction_end_date: new Date('2025-05-31T15:00:00'),
        seller_name: 'FlexiFitness',
        seller_image: 'https://randomuser.me/api/portraits/men/41.jpg',
        seller_rating: 96,
        seller_location: 'Christchurch, NZ',
        seller_member_since: new Date('2021-07-10'),
      },
      {
        title: 'Smartwatch Series X',
        description: 'Smartwatch with heart rate monitor, GPS, and waterproof design.',
        start_price: 120,
        reserve_price: 1,
        buy_now_price: 180,
        current_bid: [],
        category: 'Electronics',
        subcategory: 'Wearables',
        location: 'Auckland, NZ',
        condition: 'Used',
        auction_start_date: new Date('2025-04-27T09:00:00'),
        auction_end_date: new Date('2025-06-01T17:00:00'),
        seller_name: 'TechDealsNZ',
        seller_image: 'https://randomuser.me/api/portraits/women/30.jpg',
        seller_rating: 90,
        seller_location: 'Auckland, NZ',
        seller_member_since: new Date('2020-12-01'),
      },
      {
        title: 'Coffee Maker',
        description: 'Automatic drip coffee maker with programmable timer.',
        start_price: 45,
        reserve_price: 1,
        buy_now_price: 80,
        current_bid: [50],
        category: 'Appliances',
        subcategory: 'Kitchen',
        location: 'Hamilton, NZ',
        condition: 'New',
        auction_start_date: new Date('2025-04-28T12:00:00'),
        auction_end_date: new Date('2025-06-02T19:00:00'),
        seller_name: 'HomeEssentialsNZ',
        seller_image: 'https://randomuser.me/api/portraits/men/51.jpg',
        seller_rating: 94,
        seller_location: 'Hamilton, NZ',
        seller_member_since: new Date('2023-01-05'),
      },
      {
        title: 'Electric Kettle',
        description: 'Fast-boil electric kettle with automatic shutoff.',
        start_price: 25,
        reserve_price: 1,
        buy_now_price: 40,
        current_bid: [],
        category: 'Appliances',
        subcategory: 'Kitchen',
        location: 'Wellington, NZ',
        condition: 'New',
        auction_start_date: new Date('2025-04-29T08:00:00'),
        auction_end_date: new Date('2025-06-03T14:00:00'),
        seller_name: 'HomeEssentialsNZ',
        seller_image: 'https://randomuser.me/api/portraits/men/51.jpg',
        seller_rating: 94,
        seller_location: 'Hamilton, NZ',
        seller_member_since: new Date('2023-01-05'),
      },
      {
        title: 'Men\'s Running Shoes',
        description: 'Lightweight running shoes for everyday training.',
        start_price: 80,
        reserve_price: 1,
        buy_now_price: 120,
        current_bid: [85, 90, 95],
        category: 'Fashion',
        subcategory: 'Footwear',
        location: 'Auckland, NZ',
        condition: 'New',
        auction_start_date: new Date('2025-04-30T10:00:00'),
        auction_end_date: new Date('2025-06-04T20:00:00'),
        seller_name: 'SpeedGearNZ',
        seller_image: 'https://randomuser.me/api/portraits/men/28.jpg',
        seller_rating: 92,
        seller_location: 'Auckland, NZ',
        seller_member_since: new Date('2022-11-11'),
      },
      {
        title: 'Wireless Earbuds',
        description: 'Noise-cancelling wireless earbuds with long battery life.',
        start_price: 100,
        reserve_price: 1,
        buy_now_price: 160,
        current_bid: [],
        category: 'Electronics',
        subcategory: 'Audio',
        location: 'Christchurch, NZ',
        condition: 'New',
        auction_start_date: new Date('2025-05-01T11:00:00'),
        auction_end_date: new Date('2025-06-05T17:00:00'),
        seller_name: 'SoundWaveNZ',
        seller_image: 'https://randomuser.me/api/portraits/women/44.jpg',
        seller_rating: 95,
        seller_location: 'Wellington, NZ',
        seller_member_since: new Date('2022-03-20'),
      },
      {
        title: 'Indoor Plant Set',
        description: 'Set of 3 easy-care indoor plants in ceramic pots.',
        start_price: 35,
        reserve_price: 1,
        buy_now_price: 55,
        current_bid: [40],
        category: 'Home & Garden',
        subcategory: 'Plants',
        location: 'Hamilton, NZ',
        condition: 'New',
        auction_start_date: new Date('2025-05-02T09:00:00'),
        auction_end_date: new Date('2025-06-06T16:00:00'),
        seller_name: 'GreenThumbNZ',
        seller_image: 'https://randomuser.me/api/portraits/women/49.jpg',
        seller_rating: 99,
        seller_location: 'Hamilton, NZ',
        seller_member_since: new Date('2023-04-15'),
      },
      {
        title: 'Art Easel',
        description: 'Adjustable wooden easel for painting or display.',
        start_price: 60,
        reserve_price: 1,
        buy_now_price: 100,
        current_bid: [],
        category: 'Art Supplies',
        subcategory: 'Easels',
        location: 'Wellington, NZ',
        condition: 'New',
        auction_start_date: new Date('2025-05-03T10:00:00'),
        auction_end_date: new Date('2025-06-07T18:00:00'),
        seller_name: 'CreativeCornerNZ',
        seller_image: 'https://randomuser.me/api/portraits/men/53.jpg',
        seller_rating: 93,
        seller_location: 'Wellington, NZ',
        seller_member_since: new Date('2021-09-09'),
      },
      {
        title: 'Graphic Tablet',
        description: 'Digital drawing tablet with stylus for graphic design.',
        start_price: 110,
        reserve_price: 1,
        buy_now_price: 170,
        current_bid: [115, 125],
        category: 'Electronics',
        subcategory: 'Tablets',
        location: 'Auckland, NZ',
        condition: 'New',
        auction_start_date: new Date('2025-05-04T11:00:00'),
        auction_end_date: new Date('2025-06-08T17:00:00'),
        seller_name: 'TechDealsNZ',
        seller_image: 'https://randomuser.me/api/portraits/women/30.jpg',
        seller_rating: 90,
        seller_location: 'Auckland, NZ',
        seller_member_since: new Date('2020-12-01'),
      }
    ];

    // Insert the sample products into MongoDB
    Product.insertMany(products)
      .then((docs) => {
        console.log(`${docs.length} products added successfully!`);
        mongoose.connection.close(); // Close the connection after inserting
      })
      .catch((err) => {
        console.error('Error inserting products:', err);
        mongoose.connection.close(); // Close the connection on error as well
      });
  })
  .catch((err) => {
    console.error('Error connecting to MongoDB:', err);
  });
