const mongoose = require('mongoose');
const Product = require('./models/product');  // Assuming product schema is in 'models/product'

// Connect to MongoDB
mongoose.connect('mongodb://127.0.0.1:27017/mission-05', {
})
  .then(() => {
    console.log("Connected to MongoDB!");

    // Sample products
    const products = [
      {
        title: 'Ergonomic Office Chair',
        description: 'Comfortable ergonomic chair with adjustable armrests and lumbar support. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
        start_price: 120,
        reserve_price: 180,
        buy_now_price: 220,
        current_bid: 140,
        image: 'https://www.smartofficefurniture.co.nz/cdn/shop/files/mondo-brook-mesh-mid-back-chair-smart-office-furniture.webp?v=1733892315&width=533',
        category: 'Furniture',
        subcategory: 'Office Chairs',
        location: 'Auckland, NZ',
        condition: 'New',
        auction_start_date: new Date('2025-04-10T10:00:00'),
        auction_end_date: new Date('2025-04-15T17:00:00'),
        seller_name: 'OfficeMartNZ',
        seller_image: 'https://randomuser.me/api/portraits/men/32.jpg',
        seller_rating: 98,
        seller_location: 'Auckland, NZ',
        seller_member_since: new Date('2021-02-15'),
      },
      {
        title: 'Standing Desk',
        description: 'Adjustable standing desk with electric height adjustment.',
        start_price: 350,
        reserve_price: 500,
        buy_now_price: 620,
        current_bid: 410,
        image: 'https://standdesk.nz/wp-content/uploads/2023/07/1500-walnut-black.jpg',
        category: 'Furniture',
        subcategory: 'Desks',
        location: 'Wellington, NZ',
        condition: 'New',
        auction_start_date: new Date('2025-04-12T09:00:00'),
        auction_end_date: new Date('2025-04-20T18:00:00'),
        seller_name: 'WorkSpaceGear',
        seller_image: 'https://randomuser.me/api/portraits/women/45.jpg',
        seller_rating: 95,
        seller_location: 'Wellington, NZ',
        seller_member_since: new Date('2020-08-30'),
      },
      {
        title: 'Gaming Laptop',
        description: 'High-performance laptop with RTX graphics card and 16GB RAM for gaming.',
        start_price: 1500,
        reserve_price: 2000,
        buy_now_price: 2300,
        current_bid: 1650,
        image: 'https://i.dell.com/is/image/DellContent/content/dam/ss2/product-images/dell-client-products/notebooks/g-series/g16-7630/media-gallery/black/notebook-g16-7630-nt-black-gallery-1.psd?fmt=pjpg&pscan=auto&scl=1&wid=3510&hei=2635&qlt=100,1&resMode=sharp2&size=3510,2635&chrss=full&imwidth=5000',
        category: 'Electronics',
        subcategory: 'Laptops',
        location: 'Auckland, NZ',
        condition: 'Used',
        auction_start_date: new Date('2025-04-10T12:00:00'),
        auction_end_date: new Date('2025-04-14T19:00:00'),
        seller_name: 'NZTechSales',
        seller_image: 'https://randomuser.me/api/portraits/men/29.jpg',
        seller_rating: 91,
        seller_location: 'Auckland, NZ',
        seller_member_since: new Date('2019-05-10'),
      },
      {
        title: 'LED Monitor 24" Full HD',
        description: 'Full HD LED monitor with 144Hz refresh rate, perfect for gaming.',
        start_price: 250,
        reserve_price: 350,
        buy_now_price: 400,
        current_bid: 300,
        image: 'https://i.dell.com/is/image/DellContent//content/dam/images/products/electronics-and-accessories/dell/monitors/s-series/s2421hn/s2421hn-cfp-00025lf095-gy.psd?fmt=pjpg&pscan=auto&scl=1&wid=3488&hei=2974&qlt=100,1&resMode=sharp2&size=3488,2974&chrss=full&imwidth=5000',
        category: 'Electronics',
        subcategory: 'Monitors',
        location: 'Christchurch, NZ',
        condition: 'New',
        auction_start_date: new Date('2025-04-15T14:00:00'),
        auction_end_date: new Date('2025-04-22T16:00:00'),
        seller_name: 'VisualTechNZ',
        seller_image: 'https://randomuser.me/api/portraits/women/12.jpg',
        seller_rating: 97,
        seller_location: 'Christchurch, NZ',
        seller_member_since: new Date('2022-01-01'),
      },
      {
        title: 'Wireless Mouse',
        description: 'Ergonomic wireless mouse with long battery life and fast response.',
        start_price: 30,
        reserve_price: 50,
        buy_now_price: 65,
        current_bid: 38,
        image: 'https://assets.kogan.com/images/mightyape/MPE-30820052/1-2fbbd54b15-218216385.jpeg?auto=webp&bg-color=fff&canvas=1200%2C800&dpr=1&enable=upscale&fit=bounds&height=800&quality=90&width=1200',
        category: 'Accessories',
        subcategory: 'Mice',
        location: 'Hamilton, NZ',
        condition: 'New',
        auction_start_date: new Date('2025-04-18T08:00:00'),
        auction_end_date: new Date('2025-04-25T15:00:00'),
        seller_name: 'ClickZoneNZ',
        seller_image: 'https://randomuser.me/api/portraits/men/57.jpg',
        seller_rating: 92,
        seller_location: 'Hamilton, NZ',
        seller_member_since: new Date('2023-06-25'),
      },
      {
        title: 'Mesh Executive Chair',
        description: 'Breathable mesh executive chair with headrest and adjustable features.',
        start_price: 160,
        reserve_price: 200,
        buy_now_price: 260,
        current_bid: 180,
        image: 'https://assets.kogan.com/images/mightyape/MPE-33543998/1-a3ae920908-233716943.jpeg?auto=webp&bg-color=fff&canvas=1200%2C800&dpr=1&enable=upscale&fit=bounds&height=800&quality=90&width=1200',
        category: 'Furniture',
        subcategory: 'Office Chairs',
        location: 'Auckland, NZ',
        condition: 'New',
        auction_start_date: new Date('2025-04-16T09:00:00'),
        auction_end_date: new Date('2025-04-21T17:00:00'),
        seller_name: 'OfficeMartNZ',
        seller_image: 'https://randomuser.me/api/portraits/men/32.jpg',
        seller_rating: 98,
        seller_location: 'Auckland, NZ',
        seller_member_since: new Date('2021-02-15'),
      },
      {
        title: 'Modern Office Desk',
        description: 'Spacious office desk with drawer units and cable management.',
        start_price: 280,
        reserve_price: 350,
        buy_now_price: 400,
        current_bid: 300,
        image: 'https://assets.kogan.com/images/mightyape/MPE-38394367/1-be4e390082-310948439.jpeg?auto=webp&bg-color=fff&canvas=1200%2C800&dpr=1&enable=upscale&fit=bounds&height=800&quality=90&width=1200',
        category: 'Furniture',
        subcategory: 'Desks',
        location: 'Auckland, NZ',
        condition: 'New',
        auction_start_date: new Date('2025-04-17T10:30:00'),
        auction_end_date: new Date('2025-04-24T18:00:00'),
        seller_name: 'OfficeMartNZ',
        seller_image: 'https://randomuser.me/api/portraits/men/32.jpg',
        seller_rating: 98,
        seller_location: 'Auckland, NZ',
        seller_member_since: new Date('2021-02-15'),
      },
      {
        title: 'Filing Cabinet - 4 Drawer',
        description: 'Durable metal cabinet with lockable drawers for office use.',
        start_price: 100,
        reserve_price: 150,
        buy_now_price: 180,
        current_bid: 120,
        image: 'https://www.warehousestationery.co.nz/dw/image/v2/AAWO_PRD/on/demandware.static/-/Sites-wsl-master-catalog/default/dw3d0efb3c/53/57/W2248746_30.jpg?sw=232&sh=232&sm=fit',
        category: 'Furniture',
        subcategory: 'Storage',
        location: 'Auckland, NZ',
        condition: 'New',
        auction_start_date: new Date('2025-04-14T11:00:00'),
        auction_end_date: new Date('2025-04-21T15:30:00'),
        seller_name: 'OfficeMartNZ',
        seller_image: 'https://randomuser.me/api/portraits/men/32.jpg',
        seller_rating: 98,
        seller_location: 'Auckland, NZ',
        seller_member_since: new Date('2021-02-15'),
      },
      {
        title: 'Ergo Footrest for Desk',
        description: 'Adjustable ergonomic footrest to reduce pressure and improve posture.',
        start_price: 45,
        reserve_price: 60,
        buy_now_price: 75,
        current_bid: 48,
        image: 'https://assets.kogan.com/images/mightyape/MPE-37977967/1-a4c662bba9-308156753.jpeg?auto=webp&bg-color=fff&canvas=1200%2C800&dpr=1&enable=upscale&fit=bounds&height=800&quality=90&width=1200',
        category: 'Accessories',
        subcategory: 'Office Accessories',
        location: 'Auckland, NZ',
        condition: 'New',
        auction_start_date: new Date('2025-04-19T13:00:00'),
        auction_end_date: new Date('2025-04-26T17:00:00'),
        seller_name: 'OfficeMartNZ',
        seller_image: 'https://randomuser.me/api/portraits/men/32.jpg',
        seller_rating: 98,
        seller_location: 'Auckland, NZ',
        seller_member_since: new Date('2021-02-15'),
      },
      {
        title: 'Desk Lamp with USB Port',
        description: 'LED desk lamp with adjustable brightness and built-in USB charging port.',
        start_price: 35,
        reserve_price: 50,
        buy_now_price: 65,
        current_bid: 42,
        image: 'https://www.pbtech.co.nz/imgprod/H/O/HOMSPB3309__5.jpg?h=416317244',
        category: 'Accessories',
        subcategory: 'Lighting',
        location: 'Auckland, NZ',
        condition: 'New',
        auction_start_date: new Date('2025-04-20T08:00:00'),
        auction_end_date: new Date('2025-04-27T14:00:00'),
        seller_name: 'OfficeMartNZ',
        seller_image: 'https://randomuser.me/api/portraits/men/32.jpg',
        seller_rating: 98,
        seller_location: 'Auckland, NZ',
        seller_member_since: new Date('2021-02-15'),
      }
    ];

    // Insert the sample products into MongoDB
    Product.insertMany(products)
      .then((docs) => {
        console.log(`${docs.length} products added successfully!`);
        mongoose.connection.close(); // Close the connection after inserting
      })
      .catch((err) => {
        console.error('Error inserting products:', err);
        mongoose.connection.close(); // Close the connection on error as well
      });
  })
  .catch((err) => {
    console.error('Error connecting to MongoDB:', err);
  });
